/**
 * Site information architecture and delivery phases.
 * Public sections 1–20 ship first as a bilingual site.
 * Admin 21–34 needs auth + database.
 * Extensions 35–45 come after content ops are stable.
 */
export const siteMap = {
  routes: [
    { path: "/", name: "Domov" },
    { path: "/about", name: "O Filipovi (+ profil, tréning)" },
    { path: "/journey", name: "Športová cesta" },
    { path: "/results", name: "Výsledky + kalendár + rebríčky" },
    { path: "/usa", name: "USA – štúdium a tenis" },
    { path: "/media", name: "Foto, video, novinky, press" },
    { path: "/partners", name: "Partneri, sponzori, media kit" },
    { path: "/contact", name: "Kontakt a FAQ" },
  ],
  public: [
    { id: "top", name: "Domov / Hero" },
    { id: "about", name: "O Filipovi" },
    { id: "journey", name: "Športová cesta" },
    { id: "profile", name: "Profil hráča" },
    { id: "results", name: "Výsledky a štatistiky" },
    { id: "calendar", name: "Kalendár turnajov" },
    { id: "rankings", name: "Rebríčky" },
    { id: "training", name: "Tréning a príprava" },
    { id: "usa", name: "USA – štúdium a tenis" },
    { id: "gallery", name: "Fotogaléria" },
    { id: "videos", name: "Videogaléria" },
    { id: "news", name: "Novinky a blog" },
    { id: "press", name: "Médiá a rozhovory" },
    { id: "partners", name: "Partneri a sponzori" },
    { id: "sponsors", name: "Pre potenciálnych sponzorov" },
    { id: "media-kit", name: "Media Kit" },
    { id: "collaborate", name: "Spolupráca a partnerstvo" },
    { id: "community", name: "Komunita / charita" },
    { id: "faq", name: "FAQ" },
    { id: "contact", name: "Kontakt" },
  ],
  admin: [
    "Dashboard",
    "Turnaje",
    "Výsledky",
    "Rebríčky",
    "Galéria",
    "Videá",
    "Novinky",
    "Partneri",
    "Media Kit",
    "Kontakty / dopyty",
    "SEO",
    "Analytika",
    "Používatelia",
    "Nastavenia webu",
  ],
  future: [
    "AI asistent",
    "Interaktívna časová os",
    "Match Tracker",
    "Štatistiky výkonnosti",
    "Newsletter",
    "Partnerský portál",
    "Fan zóna",
    "E-shop",
    "Online podpora",
    "Ďalšie jazyky",
    "PWA",
  ],
} as const;
