import type { Content } from "./types";

export const en: Content = {
  meta: {
    title: "Filip Urbanos | Tennis",
    description:
      "Official site of Slovak junior tennis player Filip Urbanos — profile, journey, results, USA chapter, media, and partnerships.",
  },
  nav: {
    about: "Story",
    journey: "Journey",
    results: "Results",
    usa: "USA",
    media: "Media",
    partners: "Partners",
    contact: "Contact",
  },
  hero: {
    role: "Junior · Slovakia → Florida",
    headline: "Filip Urbanos",
    tagline: "Ready for the next point.",
    ctaPrimary: "View results",
    ctaSecondary: "Become a partner",
  },
  homeHub: {
    eyebrow: "Chapters",
    title: "Three ways in",
    lead: "The player story, results on tour, and the current USA chapter.",
    cards: {
      about: "Who Filip is and where he’s headed.",
      results: "Results, calendar, and rankings.",
      usa: "Study and tennis in Florida.",
    },
    moreLabel: "More",
  },
  about: {
    eyebrow: "About Filip",
    title: "Ambition, discipline, growth",
    outlineTitle: "Junior · SK",
    lead: "A Slovak junior with a clear aim and a routine built on training and matches.",
    photoAlt: "Filip Urbanos — on the bench before training",
    paragraphs: [
      "Filip Urbanos is a 196 cm right-hander with a hard-court preference. He has played tennis since age four or five and now competes on the ITF Junior Tour.",
      "The goal is Top 20 ATP — through discipline, tough matches, and daily preparation. Profile and training sit below; the chapter path has its own page.",
    ],
  },
  journey: {
    eyebrow: "One direction",
    title: "Forward.",
    outlineTitle: "SK · SRB · BCN · FL",
    lead: "Each chapter added pace, tougher opponents, and a clearer aim.",
    chapters: [
      {
        year: "01",
        title: "Slovakia",
        body: "Where the love for tennis and the first big ambitions began.",
      },
      {
        year: "02",
        title: "Serbia",
        body: "Training blocks in Serbia at different intervals — international preparation and clay-court work away from home.",
      },
      {
        year: "03",
        title: "Barcelona",
        body: "International training and a new view of the game.",
      },
      {
        year: "04",
        title: "Florida",
        body: "Study and training at Inspiration Academy, building match experience in the USA.",
      },
      {
        year: "05",
        title: "Future",
        body: "College tennis and a long-term path toward the professional tour.",
      },
    ],
  },
  profile: {
    eyebrow: "Player profile",
    title: "Quick facts",
    lead: "A fast overview for coaches, media, recruiting, and partners.",
    facts: [
      { label: "Goal", value: "Top 20 ATP" },
      { label: "Height", value: "196 cm" },
      { label: "Surface", value: "Hard" },
      { label: "Plays", value: "Right-handed" },
      { label: "Country", value: "Slovakia" },
      { label: "Started", value: "Age 4–5" },
    ],
  },
  results: {
    eyebrow: "Results",
    title: "Completed tournaments",
    pageTitle: "Circuit.",
    outlineTitle: "ITF · UTR · Calendar",
    pageLead:
      "Calendar, completed events, and rankings — all in one place.",
    lead: "Tournaments and milestones from Filip’s path.",
    columns: {
      date: "Date",
      event: "Event",
      place: "Place",
      surface: "Surface",
      singles: "Singles",
      doubles: "Doubles",
    },
    items: [
      {
        date: "2026-02",
        event: "J30 Nairobi",
        place: "Nairobi, Kenya",
        surface: "Clay",
        resultSingles: "Seeded #2",
        resultDoubles: "—",
      },
      {
        date: "2025",
        event: "Slovak Championships — doubles",
        place: "Slovakia",
        surface: "Hard",
        resultSingles: "—",
        resultDoubles: "Runner-up",
      },
    ],
    detailNotes: "Notes",
    detailMatches: "Matches",
    detailMedia: "Photos & videos",
    detailLink: "Official results",
    expandLabel: "Open tournament detail",
    collapseLabel: "Close detail",
  },
  live: {
    eyebrow: "Current tournament",
    title: "In play",
    lead: "Live event — we’ll add each match result here. When it ends, it moves to completed.",
    badge: "LIVE",
    empty: "No live tournament is set right now.",
    drawLabel: "Draw / live scoring",
    matchesLabel: "Matches",
    noMatches: "Matches will appear once the tournament starts.",
    resultLabels: {
      scheduled: "Scheduled",
      win: "Win",
      loss: "Loss",
      retired: "Retired",
      walkover: "Walkover",
    },
  },
  calendar: {
    eyebrow: "Calendar",
    title: "Up next",
    lead: "Circuit plan — venues and dates can shift with draws and travel.",
    items: [],
    empty: "No upcoming tournaments scheduled yet.",
    note: "",
    linkLabel: "Link",
  },
  rankings: {
    eyebrow: "Rankings",
    title: "ITF · UTR · WTN",
    lead: "Verified positions and milestones. We add more numbers once they’re confirmed from official sources.",
    empty:
      "Current numbers are added as they land. Meanwhile, see Filip’s official ITF profile.",
    profileLink: "ITF profile",
    systems: {
      "ITF Junior": "ITF singles",
      "ITF Doubles": "ITF doubles",
      UTR: "UTR singles",
      "UTR Doubles": "UTR doubles",
      WTN: "WTN singles",
      "WTN Doubles": "WTN doubles",
      ATP: "ATP",
      "Tennis Europe": "Tennis Europe",
    },
    groups: {
      ITF: "ITF",
      UTR: "UTR",
      WTN: "WTN",
      ATP: "ATP",
      "Tennis Europe": "Tennis Europe",
    },
    disciplines: {
      singles: "Singles",
      doubles: "Doubles",
    },
    items: [
      {
        system: "WTN",
        value: "24.3",
        note: "Current World Tennis Number in singles.",
      },
      {
        system: "WTN Doubles",
        value: "24.3",
        note: "Current World Tennis Number in doubles.",
      },
      {
        system: "Tennis Europe",
        value: "~150",
        note: "Historical junior milestone",
      },
    ],
  },
  training: {
    eyebrow: "Training",
    title: "Preparation for the next level",
    lead: "Tennis, conditioning, recovery, and mental work — the rhythm between tournaments.",
    items: [
      {
        title: "On court",
        body: "Technique, patterns, serve and return under international pressure.",
      },
      {
        title: "Conditioning",
        body: "Strength, mobility, and endurance for a 196 cm frame — without unnecessary injury risk.",
      },
      {
        title: "Recovery",
        body: "Physio, sleep, and recovery as part of performance, not an afterthought.",
      },
    ],
  },
  usa: {
    eyebrow: "USA",
    title: "Florida — study and tennis",
    lead: "Inspiration Academy in Bradenton combines school and high-performance tennis — Filip’s current USA chapter.",
    outlineTitle: "Bradenton · FL",
    photoAlt: "Filip Urbanos — Inspiration Academy Tennis",
    photoCaption: "Bradenton · Inspiration Academy",
    schoolBadge: "Inspiration Academy Lions",
    points: [
      "Study and daily training at Inspiration Academy in Florida.",
      "Hard-court rhythm, strong competition, and a clear daily plan.",
      "Match experience on the UTR and American junior circuit.",
      "Aim: college tennis and a long-term path to the pro tour.",
    ],
    school: {
      eyebrow: "The school",
      title: "Inspiration Academy",
      lead: "A private school in Bradenton, FL, that pairs academics with a tennis academy — one campus, one rhythm.",
      facts: [
        { label: "Location", value: "Bradenton, Florida" },
        { label: "Academics", value: "Secondary · grades 6–12 + post-grad" },
        { label: "Model", value: "Small groups · mentorship learning" },
        { label: "Tennis", value: "Full-time academy on hard courts" },
      ],
      paragraphs: [
        "Inspiration Academy is a day and boarding school built around personal instruction. Academics run alongside sport so players can handle coursework and a demanding training week.",
        "The tennis academy on the same campus gives Filip daily hard-court work, match prep, and access to events around Bradenton / Sarasota — including UTR events like Battle on the Bay.",
      ],
      linkLabel: "inspirationacademy.com",
      linkHref: "https://inspirationacademy.com/",
    },
    life: {
      eyebrow: "Day to day",
      title: "What the Florida chapter means",
      lead: "A regime where school and tennis reinforce each other — not just a change of country.",
      items: [
        {
          title: "School + court",
          body: "The day is built around learning and training. Small classes and a mentorship model make it possible to manage both.",
        },
        {
          title: "Hard-court rhythm",
          body: "Florida means outdoor hard courts, heat, and a dense calendar. Filip learns American tempo against strong competition.",
        },
        {
          title: "Matches nearby",
          body: "UTR and junior events in Bradenton / Sarasota build experience without flying halfway around the world every weekend.",
        },
        {
          title: "Next goal",
          body: "College tennis in the USA and growth toward the pro tour — Inspiration Academy is a practical platform for that path.",
        },
      ],
    },
  },
  gallery: {
    eyebrow: "Photos from the road",
    title: "Media.",
    lead: "Tournaments, training, and moments — open an album by event.",
    outlineTitle: "Life in motion.",
  },
  albums: {
    all: "All moments",
    allLead: "The full gallery across tournaments and training.",
    uncategorized: "Uncategorized",
    indexLabel: "Albums",
    back: "Back to albums",
    videosLabel: "Videos",
    empty: "No photos or videos in this album yet.",
    emptyIndex: "No albums are ready yet.",
  },
  news: {
    eyebrow: "News",
    title: "What’s new",
    lead: "Short updates from the circuit and preparation.",
    items: [
      {
        date: "2026",
        title: "Official website is live",
        excerpt:
          "A home for profile, results, media, and partnerships — in Slovak and English.",
      },
    ],
  },
  press: {
    eyebrow: "Press",
    title: "Interviews and coverage",
    lead: "Links for journalists and fans. Request the media kit via Contact.",
    items: [
      {
        type: "Profile",
        title: "ITF Junior Player Profile",
        source: "itftennis.com",
        href: "https://www.itftennis.com/en/players/filip-urbanos/800621234/svk/jt/S/overview/",
      },
      {
        type: "Academy",
        title: "Barcelona Tennis Academy — player profile",
        source: "btatennis.com",
        href: "https://www.btatennis.com/bta-players/filip-urbanos",
      },
      {
        type: "Partnerships",
        title: "Sponsoo — sponsorship profile",
        source: "sponsoo.com",
        href: "https://www.sponsoo.com/p/filipurbanos",
      },
      {
        type: "Social",
        title: "Instagram @filipurbanos",
        source: "instagram.com",
        href: "https://www.instagram.com/filipurbanos/",
      },
    ],
  },
  partners: {
    eyebrow: "Partners",
    title: "Brands with Filip",
    lead: "Thank you to the partners behind the journey — from training to tournaments.",
    outlineTitle: "Shared journey.",
    mainLabel: "Main partner",
    othersLabel: "Partners",
    emptyNote: "The space is open for additional long-term partners and collaborations.",
    visitLabel: "Visit website",
  },
  sponsors: {
    eyebrow: "For sponsors",
    title: "Why partner with Filip",
    lead: "One partnership — visibility on tour, content, and a media kit on request.",
    offerTitle: "What a partner gets",
    offers: [
      "Logo visibility on clothing and equipment",
      "Mentions on Instagram and in media posts",
      "Brand presence at tournaments",
      "Media kit (bio, photos, fact sheet) on request",
    ],
    usageTitle: "Where support goes",
    usage: [
      "Travel and lodging for ITF events",
      "Equipment, coaching, and physiotherapy",
      "Study and training block in the USA",
    ],
    cta: "Talk partnerships",
  },
  faq: {
    eyebrow: "FAQ",
    title: "Frequently asked questions",
    lead: "Quick answers for media, partners, and fans.",
    items: [
      {
        q: "Where does Filip train?",
        a: "The path ran through Love 4 Tennis in Bratislava, training blocks in Serbia, Barcelona Tennis Academy, and now Inspiration Academy in Florida.",
      },
      {
        q: "How can I sponsor Filip?",
        a: "Write to urbanosfilip33@gmail.com with a brand brief. We’ll propose a collaboration and share the media kit. The main partner is AGROMEPA, s.r.o.",
      },
      {
        q: "Where are official results?",
        a: "On the ITF profile and increasingly here under Results.",
      },
      {
        q: "Is the site available in English?",
        a: "Yes — use the SK / EN toggle in the header.",
      },
    ],
  },
  contact: {
    eyebrow: "Contact",
    title: "Let’s talk",
    outlineTitle: "Filip Urbanos",
    lead: "Media, tournaments, recruiting, and partnerships — write and we’ll get back to you.",
    emailLabel: "Email",
    socialLabel: "Instagram",
    partnerLabel: "Partnerships",
    partnerBody:
      "Send a short brand brief and goal — we’ll come back with a format that fits.",
    mediaLabel: "Media & invites",
    mediaBody:
      "Interviews, photo/video requests, and tournament invites go through the same inbox.",
    cta: "Send an email",
    detailsTitle: "Contact details",
    role: "Junior tennis player · Slovakia → Florida",
    baseLabel: "Base",
    baseValue: "Inspiration Academy · Florida, USA",
    itfLabel: "ITF profile",
    responseLabel: "Response",
    responseValue: "Usually within 2–3 days",
    igCta: "Open Instagram",
    form: {
      eyebrow: "Write to us",
      title: "Contact form",
      lead: "Partnerships, media, or another request — we usually reply within 2–3 days.",
      name: "Name",
      email: "Email",
      topic: "Topic",
      message: "Message",
      submit: "Send",
      sending: "Sending…",
      success: "Thanks — we’ve got your message.",
      error: "Couldn’t send. Try again or email us directly.",
      topics: {
        partner: "Partnership / sponsorship",
        media: "Media / interview",
        other: "Other",
      },
    },
  },
  footer: {
    rights: "© Filip Urbanos. All rights reserved.",
    tagline: "Slovakia → USA",
    instagram: "Instagram ↗",
  },
  chrome: {
    menu: "Menu",
    nav: "Primary navigation",
    lang: "Language",
  },
};
